Shop/Shop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from Shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master/',views.Master,name='master'),
    path('',views.Index,name='index'),
    path('signup/',views.signup,name='signup'),
    path('accounts/',include('django.contrib.auth.urls')),
    #add cart
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/', views.cart_detail, name='cart_detail'),
#addcontact
    path('contact_us/',views.Contact_Page,name='contact_page'),
    #Checkout
    path('checkout/',views.CheckOut,name="checkout"),
    #order
    path('order/',views.Your_Order,name="order"),

#produc_page
    path('product/',views.Product_Page,name='product_page'),

#produc_detail
   path('product/<str:id>',views.Product_Detail, name='product_detail'),

   path('search/', views.Search, name='search'),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Shop/app/models.py
import datetime

from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.contrib.auth.models import User
from django import forms


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Sub_Category(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    Availability = (('In Stock','In Stock'),('Out of Stock','Out of Stock'))

    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=False, default='')
    sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE, null=False, default='')
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE,null=True)
    image = models.ImageField(upload_to='ecommerce/pimg')
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    Availability = models.CharField(choices= Availability,null=True,max_length=100)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email', error_messages={'exist': 'email existe'})

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['password1'].widget.attrs['placeholder'] = 'password'
        self.fields['password2'].widget.attrs['placeholder'] = 'confirmer le mot de pass'

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError(self.fields['email'].error_message['exists'])
        return self.cleaned_data['email']


class Contact_us(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.email


class Order(models.Model):
    image = models.ImageField(upload_to='ecommerce/order/image')
    product = models.CharField(max_length=1000,default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.CharField(max_length=1000,default='')
    price = models.IntegerField()
    total = models.CharField(max_length=1000,default='')
    address = models.TextField()
    phone = models.CharField(max_length=10)
    pincode = models.CharField(max_length=10)
    date = models.DateField(default=datetime.datetime.today)

    def __str__(self):
        return self.product

Shop/templates/contact.html
{% extends 'master.html'%}
{% block body%}
	 <div id="contact-page" class="container">
    	<div class="bg">
	    	<div class="row">
	    		<div class="col-sm-12">
					<h2 class="title text-center">Contact <strong>Us</strong></h2>
					<div id="gmap" class="contact-map"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7715.720521761778!2d-17.40070801079501!3d14.776899929111469!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xec10c7e13479869%3A0xd8be52c8e0063c62!2sniarry%20boulangeri!5e0!3m2!1sfr!2ssn!4v1642683737414!5m2!1sfr!2ssn" width="100%" height="400" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
					</div>
				</div>
			</div>
    		<div class="row">
	    		<div class="col-sm-8">
	    			<div class="contact-form">
	    				<h2 class="title text-center">Get In Touch</h2>
	    				<div class="status alert alert-success" style="display: none"></div>
				    	<form id="main-contact-form" class="contact-form row" name="contact-form" method="post">
							{% csrf_token%}
				            <div class="form-group col-md-6">
				                <input type="text" name="name" class="form-control" required="required" placeholder="Name">
				            </div>
				            <div class="form-group col-md-6">
				                <input type="email" name="email" class="form-control" required="required" placeholder="Email">
				            </div>
				            <div class="form-group col-md-12">
				                <input type="text" name="subject" class="form-control" required="required" placeholder="Subject">
				            </div>
				            <div class="form-group col-md-12">
				                <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Your Message Here"></textarea>
				            </div>
				            <div class="form-group col-md-12">
				                <input type="submit" name="submit" class="btn btn-primary pull-right" value="Submit">
				            </div>
				        </form>
	    			</div>
	    		</div>
	    		<div class="col-sm-4">
	    			<div class="contact-info">
	    				<h2 class="title text-center">Contact Info</h2>
	    				<address>
	    					<p>E-Shopper Inc.</p>
							<p>Guediawaye deux boulengerie</p>
							<p></p>
							<p>Mobile: +221775448536</p>
							<p>Fix:338776654</p>
							<p>Email: mamadoundir2@gmail.com.com</p>
	    				</address>
	    				<div class="social-networks">
	    					<h2 class="title text-center">Réseaux sociaux</h2>
							<ul>
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-google-plus"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-youtube"></i></a>
								</li>
							</ul>
	    				</div>
	    			</div>
    			</div>
	    	</div>
    	</div>
    </div><!--/#contact-page-->

{% endblock%}

Shop/templates/index.html
{% extends 'master.html'%}

{%block body%}
	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>

						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">
								<!--slider--><h1><span>N</span>-NEWOYE</h1>
									<h2>Votre boutique en ligne </h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
									<button type="button" class="btn btn-default get">Savoir plus</button>
									</div>
								<div class="col-sm-6">
									<img src="/static/images/home/girl1.jpg" alt="" />
									<img src="/static/images/home/pricing.png"  class="pricing" alt="" />
								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<h1><span>N</span>-NEWOYE</h1>
									<h2>Votre boutique en ligne </h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Savoir plus</button>
								</div>
								<div class="col-sm-6">
									<img src="/static/images/home/girl2.png" class="girl img-responsive" alt="" />
									<img src="/static/images/home/pricing.png"  class="pricing" alt="" />
								</div>
							</div>

							<div class="item">
								<div class="col-sm-6">
									<h1><span>N</span>-NEWOYE</h1>
									<h2>Votre boutique en ligne </h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Savoir plus</button>
								</div>
								<div class="col-sm-6">
									<img src="/static/images/home/girl3 .jpg" class="girl img-responsive" alt="" />
									<img src="/static/images/home/pricing.png" class="pricing" alt="" />
								</div>
							</div>

						</div>

						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>

				</div>
			</div>

		</div>
	</section><!--/slider-->
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							{% for cat in category %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{cat.name}}
										</a>
									</h4>
								</div>
								<div id="{{cat.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in cat.sub_category_set.all%}
											<li><a href="/?category={{i.id}}">{{i.name}} </a></li>
											{% endfor%}

										</ul>
									</div>
								</div>
							</div>

							{% endfor%}

						</div><!--/category-products-->


						<div class="brands_products"><!--brands_products-->
							<h2>Marques</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									{% for i in brand %}
									<li><a href="/?brand={{i.id}}"> <span class="pull-right">(50)</span>{{i.name}}</a></li>
									{% endfor%}
								</ul>
							</div>
						</div><!--/brands_products-->


						<div class="shipping text-center"><!--shipping-->
							<img src="images/home/shipping.jpg" alt="" />
						</div><!--/shipping-->

					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">PRODUITS</h2>
						{% for prod in product%}

						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<img src="{{prod.image}}"/>
											<h2>cfa{{prod.price}}</h2>
											<p>{{prod.name}}</p>
											<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
										</div>
										<div class="product-overlay">
											<div class="overlay-content">
												<h2>cfa{{prod.price}}</h2>
												<p>{{prod.name}}</p>
												<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
											</div>
										</div>
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
									</ul>
								</div>
							</div>
						</div>
						{% endfor%}

					</div><!--features_items-->

					<div class="category-tab"><!--category-tab-->
						<div class="col-sm-12">
							<ul class="nav nav-tabs">
								<!--<li class="active"><a href="#tshirt" data-toggle="tab">T-Shirt</a></li>-->
								<li><a href="#blazers" data-toggle="tab">legumes</a></li>
								<li><a href="#sunglass" data-toggle="tab">fruits</a></li>
								<li><a href="#kids" data-toggle="tab">boison</a></li>

							</ul>
						</div>
						<div class="tab-content">
                         {% for prod in product%}
							<div class="tab-pane fade active in" id="legume" >

								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{{prod.image}}"  alt="" />
												<h2></h2>
												<p></p>
												<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
											</div>

										</div>
									</div>

								</div>



							</div>


							<div class="tab-pane fade" id="blazers" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{{prod.image}}" alt="" />
												<h2></h2>
												<p></p>
												<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
											</div>

										</div>
									</div>
								</div>


							</div>


							<div class="tab-pane fade" id="sunglass" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{{prod.image}}"alt="" />
												<h2></h2>
												<p></p>
												<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
											</div>

										</div>
									</div>
								</div>

							</div>


                      {% endfor%}
						</div>
					</div><!--/category-tab-->




					<div class="recommended_items"><!--recommended_items-->
						<h2 class="title text-center">produits recommandés</h2>

						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								<div class="item active">
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="{{prod.image}}" alt="" />
													<h2></h2>
													<p></p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>r</a>
												</div>

											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend2.jpg" alt="" />
													<h2></h2>
													<p></p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i></a>
												</div>

											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend3.jpg" alt="" />
													<h2></h2>
													<p></p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i></a>
												</div>

											</div>
										</div>
									</div>
								</div>
								
							</div>
							 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
								<i class="fa fa-angle-left"></i>
							  </a>
							  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
								<i class="fa fa-angle-right"></i>
							  </a>
						</div>
					</div><!--/recommended_items-->




				</div>
			</div>
		</div>
	</section>
{%endblock%}

Shop/templates/order.html
{% extends 'master.html'%}
{% block body%}
		<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="/">Home</a></li>
				  <li class="active">Details</li>
				</ol>
			</div>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
				{% for i in order %}
						<tr>
							<td class="cart_product">
								<a href=""><img src="{{i.image}}" alt="" height="200px;"></a>
							</td>
							<td class="cart_description">
								<h4><a href="">{{i.product}}</a></h4>

							</td>
							<td class="cart_price">
								<p>{{i.price}}</p>
							</td>
							<td class="cart_price">
								<div class="cart_quantity_button">
									<p>{{i.quantity}}</p>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price">{{i.total}}</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
							</td>
						</tr>
			  {%endfor%}
					</tbody>

				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->
{% endblock%}

Shop/templates/product.html
{% extends 'master.html'%}
{% block body%}

<section id="advertisement">
		<div class="container">
			<img src="images/shop/advertisement.jpg" alt="" />
		</div>
	</section>

	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->

							{% for cat in category %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{cat.name}}
										</a>
									</h4>
								</div>
								<div id="{{cat.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in cat.sub_category_set.all%}
											<li><a href="/product/?category={{i.id}}">{{i.name}} </a></li>
											{% endfor%}

										</ul>
									</div>
								</div>
							</div>

							{% endfor%}

						</div><!--/category-products-->
						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									{% for i in brand %}
									<li><a href="/product/?brand={{i.id}}"> <span class="pull-right">(50)</span>{{i.name}}</a></li>
									{% endfor%}
								</ul>
							</div>
						</div><!--/brands_products-->

						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b>$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div><!--/price-range-->

						<div class="shipping text-center"><!--shipping-->
							<img src="images/home/shipping.jpg" alt="" />
						</div><!--/shipping-->

					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Produits/h2>
						{% for prod in product%}

						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<img src="/{{prod.image}}" alt=""/>
											<h2>cfa{{prod.price}}</h2>
											<p>{{prod.name}}</p>
											<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
										</div>
										<div class="product-overlay">
											<div class="overlay-content">
												<h2>cfa{{prod.price}}</h2>
												<p>{{prod.name}}</p>
												<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Ajouter au panier</a>
											</div>
										</div>
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="{{prod.id}}"><i class="fa fa-plus-square"></i>Views Product</a></li>

									</ul>
								</div>
							</div>
						</div>
						{% endfor%}
					</div><!--features_items-->
                    	<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
				</div>
			</div>
		</div>
	</section>


{% endblock%}

Shop/templates/search.html
{% extends 'master.html'%}
{% block body%}
<section>
    <div class ="container">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Search Product</h2>
                        {% if product|length < 1 %}
                        <div class="content-404">
                        <img src="images/404/404.png" class="img-responsive" alt="" />
                        <h1><b>OPPS!</b>Nous n'avons pas pu trouver cette page</h1>
                        <p> Donc on dirait que vous avez broyé quelque chose. La page que vous recherchez est apparue et a disparu.</p>
                        <h2><a href="{% url 'index' %}">Bring me back Home</a></h2>
                    </div>
                        {% endif%}
						{% for prod in product%}

						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<img src="/{{prod.image}}" alt="" height="200px;"/>
											<h2>cfa{{prod.price}}</h2>
											<p>{{prod.name}}</p>
											<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
										<div class="product-overlay">
											<div class="overlay-content">
												<h2>cfa{{prod.price}}</h2>
												<p>{{prod.name}}</p>
												<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
											</div>
										</div>
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
									</ul>
								</div>
							</div>
						</div>
						{% endfor%}

					</div><!--features_items-->
    </div>
    </section>

{% endblock %}